---

- name: "copy: Debug"
  vars:
    msg: |
         fp_synchronize_default [ {{ fp_synchronize_default }} ]
         fp_synchronize_optional [ {{ fp_synchronize_optional }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug|bool

# Sync default
- name: "copy: Synchronize default files
         {{ fp_copy_dir }}/default
         (relative to playbooks directory)"
  import_tasks: copy/sync-default.yml
  when: fp_synchronize_default|bool
  tags: fp_copy_sync_default

# Sync optional
- name: "copy: Synchronize host specific files
         {{ fp_copy_dir }}/{{ rc_conf_hostname }}
         (relative to playbooks directory)"
  import_tasks: copy/sync-optional.yml
  when: fp_synchronize_optional|bool
  tags: fp_copy_sync_optional

# Unarch default
- name: "copy: Untar default files
         {{ fp_copy_dir }}/default.tar
         (relative to playbooks directory)"
  import_tasks: copy/unarch-default.yml
  when: fp_synchronize_default|bool
  tags: fp_copy_unarch_default

# Unarch optional
- name: "copy: Untar host specific files
         {{ fp_copy_dir }}/{{ rc_conf_hostname }}.tar
         (relative to playbooks directory)"
  import_tasks: copy/unarch-optional.yml
  when: fp_synchronize_optional|bool
  tags: fp_copy_unarch_optional

# EOF
...
