---

- name: "freebsd-update: Backup origin /etc/freebsd-update.conf"
  ansible.builtin.command:
    cmd: cp /etc/freebsd-update.conf /etc/freebsd-update.conf.orig
    creates: /etc/freebsd-update.conf.orig
  when: fp_freebsd_update_conf_orig|bool
  tags: fp_freebsd_update_conf_orig

- name: "freebsd-update: Create /etc/freebsd-update.conf from template"
  ansible.builtin.template:
    src: "{{ fp_freebsd_update_conf_template }}"
    dest: /etc/freebsd-update.conf
    owner: root
    mode: '0644'
  tags: fp_freebsd_update_conf

# EOF
...
