---

- name: "fstab: Configure fstab entries"
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state|default('mounted') }}"
    backup: "{{ fp_backup_conf }}"
  loop: "{{ fp_fstab_entries }}"

# EOF
...
