---

- name: "fstab: Configure fstab entries"
  ansible.posix.mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    dump: "{{ item.dump|default('0') }}"
    passno: "{{ item.passno|default('0') }}"
    state: "{{ item.state|default('mounted') }}"
    backup: "{{ fp_backup }}"
  loop: "{{ fp_fstab_entries }}"

# EOF
...
