---

- name: "groups: Debug (fp_groups_debug={{ fp_groups_debug }})"
  vars:
    msg: |-
      fp_groups_conf:
        {{ fp_groups_conf|to_nice_yaml|indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: fp_groups_debug|bool
  tags: fp_groups_debug

- name: "groups: Manage groups"
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid|default(omit) }}"
    local: "{{ item.local|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
    system: "{{ item.system|default(omit) }}"
  loop: "{{ fp_groups_conf }}"
  tags: fp_groups_conf

# EOF
...
