---

- name: "groups: Debug"
  vars:
    msg: |-
      fp_groups_conf
      {{ fp_groups_conf|to_nice_yaml }}
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_groups_debug|bool
  tags: [fp_groups_debug, always]

- name: "groups: Manage groups"
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid|default(omit) }}"
    local: "{{ item.local|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
    system: "{{ item.system|default(omit) }}"
  loop: "{{ fp_groups_conf }}"
  tags: fp_groups_conf

# EOF
...
