---

- name: "hostapd: Enable and start hostapd"
  when:
    - fp_hostapd_enabled|bool
    - fp_hostapd_install|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^hostapd_enable"
    line: "hostapd_enable=\"YES\""
    backup: "{{ fp_backup_conf }}"
  notify: enable and start hostapd
  tags: fp_hostapd_rcconf

- name: "hostapd: Disable and stop hostapd"
  when:
    - not fp_hostapd_enabled|bool
    - fp_hostapd_install|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^hostapd_enable"
    line: "hostapd_enable=\"NO\""
    backup: "{{ fp_backup_conf }}"
  notify: disable and stop hostapd
  tags: fp_hostapd_rcconf

- name: "hostapd: Configure interface for hostapd"
  when: fp_hostapd_enabled|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: "{{ fp_backup_conf }}"
  loop:
    - regexp: "^create_args_{{ fp_hostapd_interface }}"
      line: "create_args_{{ fp_hostapd_interface }}=\"wlanmode hostap country {{ fp_hostapd_country }}\""
    - regexp: "^wlans_{{ fp_hostapd_device }}"
      line: "wlans_{{ fp_hostapd_device }}=\"{{ fp_hostapd_interface }}\""
    - regexp: "^ifconfig_{{ fp_hostapd_interface }}"
      line: "ifconfig_{{ fp_hostapd_interface }}=\"inet {{ fp_hostapd_inet }} netmask {{ fp_hostapd_netmask }}\""
  notify: restart hostapd
  tags: fp_hostapd_rcconf

- name: "hostapd: Configure /etc/hostapd.conf template file"
  when: fp_hostapd_enabled|bool
  template:
    src: "hostapd.conf.j2"
    dest: "/etc/hostapd.conf"
    backup: "{{ fp_backup_conf }}"
  notify: restart hostapd
  tags: fp_hostapd_conf

# EOF
...
