---

- name: "hosts: Debug (fp_hosts_debug={{ fp_hosts_debug }})"
  vars:
    msg: |-
      fp_hosts_sanity: {{ fp_hosts_sanity }}
      fp_hosts_conf_file: {{ fp_hosts_conf_file }}
      fp_hosts_conf_template: {{ fp_hosts_conf_template }}
      fp_hosts_localhost_ipv4: {{ fp_hosts_localhost_ipv4 }}
      fp_hosts_localhost_ipv6: {{ fp_hosts_localhost_ipv6 }}
      fp_hosts_conf:
        {{ fp_hosts_conf|to_yaml|indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: fp_hosts_debug|bool
  tags: fp_hosts_debug

- name: "Sanity"
  block:
    - name: "hosts: Sanity valid IP"
      ansible.builtin.fail:
        msg: "[ERROR] Invalid IP address"
      when: (fp_hosts_conf|map(attribute='ip')|map('ipaddr')) is not all
    - name: "hosts: Sanity unique FQDN"
      ansible.builtin.fail:
        msg: "[ERROR] FQDN not unique"
      vars:
        no_records: "{{ fp_hosts_conf|length }}"
        no_hosts: "{{ fp_hosts_conf|map(attribute='fqdn')|list|unique|length }}"
      when: no_records != no_hosts
  when: fp_hosts_sanity|bool
  tags: fp_hosts_sanity

- name: "hosts: Configure hosts in {{ fp_hosts_conf_file }}"
  ansible.builtin.template:
    src: "{{ fp_hosts_conf_template }}"
    dest: "{{ fp_hosts_conf_file }}"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ fp_backup }}"
  tags: fp_hosts_conf

# EOF
...
