---

- name: "hosts: Debug"
  vars:
    msg: |
      fp_hosts_sanity [{{ fp_hosts_sanity }}]
      fp_hosts_localhost_IPv4 [{{ fp_hosts_localhost_IPv4 }}]
      fp_hosts_localhost_IPv6 [{{ fp_hosts_localhost_IPv6 }}]
      fp_hosts_template [{{ fp_hosts_template }}]
      fp_hosts
      {{ fp_hosts|to_yaml }}
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
  when: fp_hosts_debug|bool
  tags: fp_hosts_debug

- name: "Sanity"
  block:
    - name: "hosts: Sanity valid IP"
      fail:
        msg: "[ERROR] Invalid IP address"
      when: (fp_hosts|map(attribute='ip')|map('ipaddr')) is not all
    - name: "hosts: Sanity unique FQDN"
      fail:
        msg: "[ERROR] FQDN not unique"
      vars:
        no_records: "{{ fp_hosts|length }}"
        no_hosts: "{{ fp_hosts|map(attribute='fqdn')|list|unique|length }}"
      when: no_records != no_hosts
  when: fp_hosts_sanity|bool
  tags: fp_hosts_sanity

- name: "hosts: Configure hosts in /etc/hosts"
  template:
    src: "{{ fp_hosts_template }}"
    dest: /etc/hosts
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ fp_backup_conf }}"
  tags: fp_hosts_conf

# EOF
...
