---

- name: "login: Create {{ fp_login_conf_file }}"
  ansible.builtin.template:
    src: "{{ fp_login_conf_template }}"
    dest: "{{ fp_login_conf_file }}"
    owner: root
    group: wheel
    mode: "0644"
    backup: "{{ fp_backup }}"
  notify: rebuild login_conf
  when: fp_login_conf_global|bool

- name: "login: Create local .login_conf"
  ansible.builtin.template:
    src: "{{ fp_login_conf_template_local }}"
    dest: "/home/{{ item.user }}/.login_conf"
    owner: "{{ item.user }}"
    group: "{{ item.group|default(item.user) }}"
    mode: "0644"
    backup: "{{ fp_backup }}"
  loop: "{{ fp_login_conf_local }}"
  loop_control:
    label: "{{ item.user }}"

# EOF
...
