---

# By default system info in added to the top of /etc/motd on reboot.
# Set update_motd NO to disable this update.

- name: "motd: Configure /etc/motd"
  template:
    src: "motd.j2"
    dest: "/etc/motd"
    backup: "{{ fp_backup_conf }}"
  tags: fp_motd_create

- name: "motd: Set update_motd YES"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^update_motd"
    line: "update_motd=\"YES\""
    backup: "{{ fp_backup_conf }}"
  when: fp_update_motd|bool
  tags: fp_motd_rcconf

- name: "motd: Set update_motd NO"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^update_motd"
    line: "update_motd=\"NO\""
    backup: "{{ fp_backup_conf }}"
  when: not fp_update_motd|bool
  tags: fp_motd_rcconf

# EOF
...
