---

- name: "mount-iso: Debug"
  vars:
    msg: |
      fp_mount_iso_points_create [{{ fp_mount_iso_points_create }}]
      fp_mount_iso_entries
      {{ fp_mount_iso_entries|to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_mount_iso_debug|bool
  tags: [fp_mount_iso_debug, always]

- name: "mount-iso: Set variables"
  set_fact:
    _fp_mount_task: iso
    _fp_mount_fstype_default: cd9660
    _fp_mount_points_create: "{{ fp_mount_iso_points_create }}"
    _fp_mount_entries: "{{ fp_mount_iso_entries }}"
    _fp_mount_debug: "{{ fp_mount_iso_debug }}"

- name: "mount-iso: Import mount-vnode.yml"
  import_tasks: mount-vnode.yml

# EOF
...
