---

- name: "mount-iso: Get mounted iso"
  block:
    - name: "mount-iso: Get iso mount points"
      command: "mount -t cd9660"
      args:
        warn: false
      register: result
      changed_when: false
    - name: "mount-iso: Set empty mounted_iso_list"
      set_fact:
        mounted_iso_list: []
    - name: "mount-iso: Add entries to mounted_iso_list"
      set_fact:
        mounted_iso_list: >-
          {{ mounted_iso_list + [ {
          'mount_point': item.split(' ')[2],
          'device': item.split(' ')[0]|basename } ]
          }}
      loop: "{{ result.stdout_lines|default([]) }}"
    - name: "mount-iso: Debug"
      debug:
        var: mounted_iso_list
      when: fp_debug|bool

- name: "mount-iso: Create mount points"
  file:
    state: directory
    path: "{{ item.mount }}"
  loop: "{{ fp_mount_iso_entries }}"
  when: item.state|default("mounted") == "mounted"

- name: "mount-iso: Debug list mounted iso"
  debug:
    msg: "{{ mounted_iso_list|json_query('[].mount_point') }}"
  when: fp_debug|bool

- name: "mount-iso: Debug mount commands"
  debug:
    msg: |
      mount -t cd9660 /dev/`mdconfig -f {{ item.iso }}` {{ item.mount }}
  loop: "{{ fp_mount_iso_entries }}"
  when:
    - fp_debug|bool
    - item.mount not in mounted_iso_list|json_query('[].mount_point')
    - item.state|default("mounted") == "mounted"

- name: "mount-iso: Mount iso entries"
  shell: "mount -t cd9660 /dev/$(mdconfig -f {{ item.iso }}) {{ item.mount }}"
  args:
    warn: false
  loop: "{{ fp_mount_iso_entries }}"
  when:
    - item.mount not in mounted_iso_list|json_query('[].mount_point')
    - item.state|default("mounted") == "mounted"

- name: "mount-iso: Umount iso entries"
  mount:
    state: unmounted
    path: "{{ item.mount }}"
  loop: "{{ fp_mount_iso_entries }}"
  when:
    - item.mount in mounted_iso_list|json_query('[].mount_point')
    - item.state|default("mounted") == "unmounted"

- name: "mount-iso: Set list of nodes to be deleted"
  set_fact:
    local_node_list: "{{ local_node_list|default([]) }} + {{ mounted_iso_list|json_query(local_query) }}"
  vars:
    local_query: "[?mount_point=='{{ item.mount }}'].device"
  loop: "{{ fp_mount_iso_entries }}"
  when:
    - item.mount in mounted_iso_list|json_query('[].mount_point')
    - item.state|default("mounted") == "unmounted"

- name: "mount-iso: Debug list nodes to be deleted"
  debug:
    var: local_node_list
  when: fp_debug|bool

- name: "mount-iso: Delete nodes"
  command: "mdconfig -d -u {{ item }}"
  loop: "{{ local_node_list|default([]) }}"
  changed_when: local_node_list|default([])|length > 0
# changed_when fixed the warning. Otherwise ansible-lint reports:
# E301: Commands should not change things if nothing needs doing
# vbotka.freebsd_postinstall/tasks/mount-iso.yml:78
# Comment: There is no reason for a Warning (severity:High!) . The
# command is executed only if there are items in the list.
# Bug 336
# (https://github.com/ansible/ansible-lint/issues/336#issuecomment-450552031)

# EOF
...
