---
# https://www.freebsd.org/doc/handbook/network-nfs.html

- name: "nfs: Enable and start nfs client"
  when: fp_nfs_service_enable|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: "{{ fp_backup_conf }}"
  loop:
    - {regexp: "^\\s*nfs_client_enable\\s*=", line: "nfs_client_enable=\"YES\""}
  notify: enable and start nfs client
  tags: fp_nfs_enable_nfsclient

- name: "nfs: Disable and stop nfs client"
  when: not fp_nfs_service_enable|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: "{{ fp_backup_conf }}"
  loop:
    - {regexp: "^\\s*nfs_client_enable\\s*=", line: "nfs_client_enable=\"NO\""}
  notify: disable and stop nfs client
  tags: fp_nfs_disable_nfsclient

- name: "nfs: Enable and start lockd"
  when: fp_rpc_lockd_enable|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: "{{ fp_backup_conf }}"
  loop:
    - {regexp: "^\\s*rpc_lockd_enable\\s*=", line: "rpc_lockd_enable=\"YES\""}
  notify: enable and start lockd
  tags: fp_nfs_enable_lockd

- name: "nfs: Disable and stop lockd"
  when: not fp_rpc_lockd_enable|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: "{{ fp_backup_conf }}"
  loop:
    - {regexp: "^\\s*rpc_lockd_enable\\s*=", line: "rpc_lockd_enable=\"NO\""}
  notify: disable and stop lockd
  tags: fp_nfs_disable_lockd

- name: "nfs: Enable and start statd"
  when: fp_rpc_statd_enable|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: "{{ fp_backup_conf }}"
  loop:
    - {regexp: "^\\s*rpc_statd_enable\\s*=", line: "rpc_statd_enable=\"YES\""}
  notify: enable and start statd
  tags: fp_nfs_enable_statd

- name: "nfs: Disable and stop statd"
  when: not fp_rpc_statd_enable|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: "{{ fp_backup_conf }}"
  loop:
    - {regexp: "^\\s*rpc_statd_enable\\s*=", line: "rpc_statd_enable=\"NO\""}
  notify: disable and stop statd
  tags: fp_nfs_disable_statd

# EOF
...
