---

# nfs
- name: "nfs: Enable and start nfs client"
  when: fp_nfs_enable|bool
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_nfs_enable_rcconf }}"
  notify: enable and start nfs client
  tags: fp_nfs_rcconf

- name: "nfs: Disable and stop nfs client"
  when: not fp_nfs_enable|bool
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_nfs_disable_rcconf }}"
  notify: disable and stop nfs client
  tags: fp_nfs_rcconf

# lockd
- name: "nfs: Enable and start lockd"
  when: fp_rpc_lockd_enable|bool
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpc_lockd_enable_rcconf }}"
  notify: enable and start lockd
  tags: fp_nfs_lockd_rcconf

- name: "nfs: Disable and stop lockd"
  when: not fp_rpc_lockd_enable|bool
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpc_lockd_disable_rcconf }}"
  notify: disable and stop lockd
  tags: fp_nfs_lockd_rcconf

# statd
- name: "nfs: Enable and start statd"
  when: fp_rpc_statd_enable|bool
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpc_statd_enable_rcconf }}"
  notify: enable and start statd
  tags: fp_nfs_statd_rcconf

- name: "nfs: Disable and stop statd"
  when: not fp_rpc_statd_enable|bool
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpc_statd_disable_rcconf }}"
  notify: disable and stop statd
  tags: fp_nfs_statd_rcconf

# EOF
...
