---

- name: "nfsd: Enable and start nfs server"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_nfsd_enable_rcconf }}"
  when: fp_nfsd_enable|bool
  notify:
    - enable and start nfs server
    - enable and start rpcbind
    - enable and start mountd

- name: "nfsd: Disable and stop nfs server"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_nfsd_disable_rcconf }}"
  when: not fp_nfsd_enable|bool
  notify: disable and stop nfs server

- name: "nfsd: Enable and start lockd"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpc_lockd_enable_rcconf }}"
  when: fp_rpc_lockd_enable|bool
  notify: enable and start lockd

- name: "nfsd: Disable and stop lockd"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpc_lockd_disable_rcconf }}"
  when: not fp_rpc_lockd_enable|bool
  notify: disable and stop lockd

- name: "nfsd: Enable and start statd"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpc_statd_enable_rcconf }}"
  when: fp_rpc_statd_enable|bool
  notify: enable and start statd

- name: "nfsd: Disable and stop statd"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpc_statd_disable_rcconf }}"
  when: not fp_rpc_statd_enable|bool
  notify: disable and stop statd

- name: "nfsd: Disable and stop rpcbind"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_rpcbind_disable_rcconf }}"
  when: not fp_rpcbind_enable|bool
  notify: disable and stop rpcbind

- name: "nfsd: Disable and stop mountd"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: '{{ item.key }}="{{ item.value }}"'
    backup: "{{ fp_backup }}"
  loop: "{{ fp_mountd_disable_rconf }}"
  when: not fp_mountd_enable|bool
  notify: disable and stop mountd

- name: "nfsd: Configure /etc/exports"
  template:
    src: exports.j2
    dest: /etc/exports
    backup: "{{ fp_backup }}"
  notify: reload mountd

# EOF
...
