---

- name: "ntp: Enable and start ntpd"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*ntpd_enable\s*=(.*)$'
    line: 'ntpd_enable="YES"'
    backup: "{{ fp_backup }}"
  when: fp_ntp_enable|bool
  notify: enable and start ntpd
  tags: fp_ntp_rcconf

- name: "ntp: Disable and stop ntpd"
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*ntpd_enable\s*=(.*)$'
    line: 'ntpd_enable="NO"'
    backup: "{{ fp_backup }}"
  when: not fp_ntp_enable|bool
  notify: disable and stop ntpd
  tags: fp_ntp_rcconf

- name: "ntp: Create /etc/ntp.conf from template"
  template:
    src: "{{ fp_ntp_conf_template }}"
    dest: "{{ fp_ntp_conf_file }}"
    backup: "{{ fp_backup }}"
  notify: restart ntpd
  tags: fp_ntp_conf

# EOF
...
