---

- name: "packages: Install packages"
  include_tasks: packages-install.yml
  loop: "{{ fp_packages }}"
  when: item.enabled

# links
- name: "packages: Create symbolic links"
  file:
    src: "{{ item.target }}"
    dest: "{{ item.link }}"
    state: "link"
    force: yes
  loop: "{{ fp_links }}"
  tags: fp_packages_links

# EOF
...
