---

- name: "packages: Install packages"
  pkgng:
    name: "{{ item }}"
  loop: "{{ fp_ports }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method|lower == "packages"
  tags: fp_packages_install

- name: "packages: Install ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ fp_ports }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method|lower == "ports"
  tags: fp_packages_install

# smartmontools
- name: "packages: Install smartmontools package"
  pkgng:
    name: "sysutils/smartmontools"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "packages"
    - fp_smartd_install
  tags: fp_packages_smartmontools

- name: "packages: Install smartmontools port"
  portinstall:
    name: "sysutils/smartmontools"
    use_packages: "{{ freebsd_use_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "ports"
    - fp_smartd_install
  tags: fp_packages_smartmontools

# hostapd
- name: "packages: Install hostapd package"
  pkgng:
    name: "net/hostapd"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "packages"
    - fp_hostapd_install
  tags: fp_packages_hostapd

- name: "packages: Install hostapd port"
  portinstall:
    name: "net/hostapd"
    use_packages: "{{ freebsd_use_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "ports"
    - fp_hostapd_install
  tags: fp_packages_hostapd

# procmail
- name: "packages: Install procmail package"
  pkgng:
    name: "mail/procmail"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "packages"
    - fp_procmail_install
  tags: fp_packages_procmail

- name: "packages: Install procmail port"
  portinstall:
    name: "mail/procmail"
    use_packages: "{{ freebsd_use_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "ports"
    - fp_procmail_install
  tags: fp_packages_procmail

# apcupsd
- name: "packages: Install sysutils/apcupsd package"
  pkgng:
    name: "sysutils/apcupsd"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "packages"
    - fp_apcupsd_install
  tags: fp_packages_apcupsd

- name: "packages: Install sysutils/apcupsd port"
  portinstall:
    name: "sysutils/apcupsd"
    use_packages: "{{ freebsd_use_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "ports"
    - fp_apcupsd_install
  tags: fp_packages_apcupsd

# wpa_supplicant
- name: "packages: Install security/wpa_supplicant package"
  pkgng:
    name: "{{ item }}"
  loop: "{{ fp_wpasupplicant_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "packages"
    - fp_wpasupplicant_install
  tags: fp_packages_wpasupplicant

- name: "packages: Install security/wpa_supplicant port"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ fp_wpasupplicant_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - freebsd_install_method|lower == "ports"
    - fp_wpasupplicant_install
  tags: fp_packages_wpasupplicant

# links
- name: "packages: Create symbolic links"
  file:
    src: "{{ item.target }}"
    dest: "{{ item.link }}"
    state: "link"
    force: yes
  loop: "{{ fp_links }}"
  tags: fp_packages_links

# EOF
...
