---

- name: "packages: Debug (fp_packages_debug={{ fp_packages_debug }})"
  vars:
    msg: |-
         freebsd_install_method: {{ freebsd_install_method }}
         freebsd_use_packages: {{ freebsd_use_packages }}
         freebsd_install_retries: {{ freebsd_install_retries }}
         freebsd_install_delay: {{ freebsd_install_delay }}
         fp_install: {{ fp_install }}
         fp_pkg_autoremove: {{ fp_pkg_autoremove|default('UNDEFINED') }}
         fp_pkg_cached: {{ fp_pkg_cached|default('UNDEFINED') }}
         fp_pkg_chroot: {{ fp_pkg_chroot|default('UNDEFINED') }}
         fp_pkg_jail: {{ fp_pkg_jail|default('UNDEFINED') }}
         fp_pkg_pkgsite: {{ fp_pkg_pkgsite|default('UNDEFINED') }}
         fp_pkg_rootdir: {{ fp_pkg_rootdir|default('UNDEFINED') }}
         fp_pkg_state: {{ fp_pkg_state|default('UNDEFINED') }}

         apache_version: {{ apache_version }}
         apache_php_version: {{ apache_php_version }}
         bsd_bind_version: {{ bsd_bind_version }}
         bsd_dhcp_version: {{ bsd_dhcp_version }}
         bsd_linux_version: {{ bsd_linux_version }}
         bsd_mysql_version: {{ bsd_mysql_version }}
         bsd_perl_version: {{ bsd_perl_version }}
         bsd_php_version: {{ bsd_php_version }}
         bsd_python_version: {{ bsd_python_version }}
         bsd_ssl_version: {{ bsd_ssl_version }}

         fp_links:
           {{ fp_links|to_yaml(indent=2)|indent(2) }}
         fp_packages:
           {{ fp_packages|sort(attribute='list')|
                          items2dict(key_name='list', value_name='enabled')|
                          to_nice_yaml(indent=2)|indent(2) }}
         ansible_architecture: {{ ansible_architecture }}
         pkg_dict_{{ ansible_architecture }}:
           {{ lookup('vars', 'pkg_dict_' ~ ansible_architecture)|
              sort(attribute='pkglist')|
              items2dict(key_name='pkglist', value_name='packages')|
              to_yaml(indent=2)|indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: fp_packages_debug|bool
  tags: fp_packages_debug

- name: "packages: Install packages"
  ansible.builtin.include_tasks: packages-install.yml
  loop: "{{ fp_packages }}"
  when: item.enabled

# links
- name: "packages: Create symbolic links"
  ansible.builtin.file:
    src: "{{ item.target }}"
    dest: "{{ item.link }}"
    state: link
    force: true
  loop: "{{ fp_links }}"
  tags: fp_packages_links

# EOF
...
