---

- name: "smartd: Enable and start smartd"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^smartd_enable"
    line: "smartd_enable=\"YES\""
    backup: "{{ fp_backup_conf }}"
  when:
    - fp_smartd_service_enabled|bool
    - fp_smartd_install|bool
  notify: enable and start smartd
  tags: fp_smartd_rcconf

- name: "smartd: Disable and stop smartd"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^smartd_enable"
    line: "smartd_enable=\"NO\""
    backup: "{{ fp_backup_conf }}"
  when:
    - not fp_smartd_service_enabled|bool
    - fp_smartd_install|bool
  notify: disable and stop smartd
  tags: fp_smartd_rcconf

- name: "smartd: Configure smartd.conf"
  lineinfile:
    dest: "{{ fp_smartd_conf_file }}"
    regexp: "^DEVICESCAN"
    state: "absent"
    backup: "{{ fp_backup_conf }}"
  notify: reload smartd
  tags: fp_smartd_conf

- name: "smartd: Configure devices in {{ fp_smartd_conf_file }}"
  lineinfile:
    dest: "{{ fp_smartd_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: "{{ fp_smartd_conf_owner }}"
    group: "{{ fp_smartd_conf_group }}"
    mode: "{{ fp_smartd_conf_mode }}"
    create: true
    backup: "{{ fp_backup_conf }}"
  loop: "{{ fp_smartd_devices }}"
  notify: reload smartd
  tags: fp_smartd_conf

# EOF
...
