---

- name: "ssh: Debug"
  vars:
    msg: |
         ssh_config_path [ {{ ssh_config_path }} ]
         ssh_config
         {{ ssh_config | to_yaml }}
         sshd_config_path [ {{ sshd_config_path }} ]
         sshd_config
         {{ sshd_config | to_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug

- name: "ssh: Configure {{ ssh_config_path }}"
  template:
    src: "ssh_config.j2"
    dest: "{{ ssh_config_path }}"
    backup: "{{ fp_backup_conf }}"
  tags: fp_ssh_config

- name: "ssh: Configure {{ sshd_config_path }}"
  lineinfile:
    dest: "{{ sshd_config_path }}"
    regexp: "^{{ item.key }}"
    insertbefore: "^{{ '#' }}{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    backup: "{{ fp_backup_conf }}"
    validate: "{{ sshd_path }} -t -f %s"
  loop: "{{ sshd_config }}"
  notify: reload sshd
  tags: fp_ssh_sshd_config

- name: "ssh: Enable and start sshd"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^sshd_enable"
    line: "sshd_enable=\"YES\""
    backup: "{{ fp_backup_conf }}"
  notify: enable and start sshd
  when: sshd_enable
  tags: fp_ssh_rcconf

- name: "ssh: Disable and stop sshd"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^sshd_enable"
    line: "sshd_enable=\"NO\""
    backup: "{{ fp_backup_conf }}"
  notify: disable and stop sshd
  when: not sshd_enable
  tags: fp_ssh_rcconf

# EOF
...
