---

- name: "swap: Debug"
  vars:
    msg: |
         fp_swap [{{ fp_swap }}]
         fp_swap_file [{{ fp_swap_file|default("NOT-DEFINED") }}]
         fp_swap_md [{{ fp_swap_md|default("NOT-DEFINED") }}]
         fp_swap_size [{{ fp_swap_size|default("NOT-DEFINED") }}]
         fp_swap_stsize [{{ fp_swap_stsize|default("NOT-DEFINED") }}]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug|bool

- name: "swap: Create swapfile {{ fp_swap_file }}"
  shell: sh -c 'if [ ! -e {{ fp_swap_file }} ]; then printf "create"; fi'
  register: command_result
  changed_when: command_result.stdout == "create"
  notify: create swap
  when: fp_swap|bool

- name: "swap: Create swap entry in /etc/fstab"
  lineinfile:
    path: "/etc/fstab"
    regexp: "^{{ fp_swap_md }}"
    line: "{{ fp_swap_md }} none swap sw,file={{ fp_swap_file }},late 0 0"
    backup: "{{ fp_backup_conf }}"
  notify: mount swap
  when: fp_swap|bool
#  mount:
#    name="none"
#    src="{{ fp_swap_md }}"
#    fstype="swap"
#    opts="sw,file={{ fp_swap_file }},late"
#    passno="0"
#    dump="0"
#    state="present"
#    backup yes
# Note: mount module fstype swap does not work with FreeBSD as
# expected. Instead of adding the src all swap mount points present in
# the fstab are replaced with src.

- name: "swap: Change swapfile {{ fp_swap_file }}"
  shell: >
    sh -c 'if [ -e {{ fp_swap_file }} ] &&
    [ "`stat -f %z {{ fp_swap_file }}`" -ne "{{ fp_swap_stsize }}" ]; then
    printf "change";
    fi'
  register: command_result
  changed_when: command_result.stdout == "change"
  notify: change and mount swap
  when: fp_swap|bool

- name: Remove swap entry from /etc/fstab
  lineinfile:
    path: "/etc/fstab"
    regexp: "^{{ fp_swap_md }}"
    state: "absent"
    backup: "{{ fp_backup_conf }}"
  notify: umount and delete swap
  when:
    - not fp_swap|bool
    - fp_swap_md is defined

- meta: flush_handlers

# EOF
...
