---

- debug: msg="fp_zoneinfo [ {{ fp_zoneinfo }} ]"
  when: fp_debug|bool

- name: "timezone: set timezone to {{ fp_zoneinfo }}"
  timezone:
    name: "{{ fp_zoneinfo }}"
  notify: adjust CMOS

# EOF
...
