---

- name: "tmpmfs: Debug"
  vars:
    msg: |
         fp_tmpmfs_rcconf
         {{ fp_tmpmfs_rcconf|to_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug|bool

- name: "tmpmfs: Configure tmpmfs"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^\\s*{{ item.key }}\\s*="
    line: "{{ item.key }}=\"{{ item.value }}\""
    backup: "{{ fp_backup_conf }}"
  loop: "{{ fp_tmpmfs_rcconf }}"

# EOF
...
