---

# Sync default
- name: "copy:sync-default: Check existence of {{ role_path }}/{{ fp_copy_dir }}/default"
  stat:
    path: "{{ role_path }}/{{ fp_copy_dir }}/default"
  register: default_copy
  delegate_to: localhost

- name: "copy:sync-default: Debug directory default exists"
  debug:
    msg: "Directory default exists."
  when: fp_debug|bool and
        default_copy.stat.isdir|default(false)

- name: "copy:sync-default: Synchronize default files {{ fp_copy_dir }}/default
         (relative to playbooks directory)"
  synchronize:
    src: "{{ fp_copy_dir }}/default/"
    dest: "/"
    archive: "{{ fp_synchronize_archive }}"
    checksum: "{{ fp_synchronize_checksum }}"
    compress: "{{ fp_synchronize_compress }}"
    delete: "{{ fp_synchronize_delete }}" 
    group: "{{ fp_synchronize_group }}"
    owner: "{{ fp_synchronize_owner }}"
    perms: "{{ fp_synchronize_perms }}"
    times: "{{ fp_synchronize_times }}"
  when: default_copy.stat.isdir|default(false)

# EOF
...
