---
# devfs
- name: enable and start devfs
  ansible.builtin.service: name="devfs" state="started" enabled=true
- name: disable and stop devfs
  ansible.builtin.service: name="devfs" state="stopped" enabled=false
- name: restart devfs
  ansible.builtin.service: name="devfs" state="restarted"
  when: fp_devfs_enabled|bool
