---
# dhclient
- name: restart dhclient
  ansible.builtin.service:
    name: dhclient
    state: restarted

- name: restart dhclient all
  ansible.builtin.command:
    cmd: "/etc/rc.d/dhclient restart {{ item }}"
  loop: "{{ fp_dhclient_ifn }}"

- name: restart dhclient blocks
  ansible.builtin.command:
    cmd: "/etc/rc.d/dhclient restart {{ item }}"
  loop: "{{ fp_dhclient_conf_changes.results|
            selectattr('changed')|
            map(attribute='item.ifn')|
            unique }}"
