---
# handlers for freebsd_postinstall

- import_tasks: adjkerntz.yml
- import_tasks: apcupsd.yml
- import_tasks: devfs.yml
- import_tasks: fstab.yml
- import_tasks: hostapd.yml
- import_tasks: hostname.yml
- import_tasks: login.yml
- import_tasks: messages.yml
- import_tasks: newaliases.yml
- import_tasks: nfsd.yml
- import_tasks: nfs.yml
- import_tasks: ntpdate.yml
- import_tasks: ntpd.yml
- import_tasks: qemu.yml
- import_tasks: resolvconf.yml
- import_tasks: smartd.yml
- import_tasks: snmpd.yml
- import_tasks: sshd.yml
- import_tasks: swap.yml
- import_tasks: sysctl.yml
- import_tasks: wpasupplicant.yml

# EOF
...
