---
fp_hosts: false
fp_hosts_debug: false
fp_hosts_sanity: true
fp_hosts_conf_file: /etc/hosts
fp_hosts_conf_template: hosts.j2
fp_hosts_localhost_ipv4: "127.0.0.1"
fp_hosts_localhost_ipv6: "::1"
fp_hosts_conf: []
